<a href="https://colab.research.google.com/github/miso-20/ESSA/blob/main/ESAA_OB_WEEK_05_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

딥러닝 파이토치 교과서 ch1-2. p.18~60

# Chapter 01. 머신 러닝과 딥러닝

## 01. 인공지능, 머신 러닝과 딥러닝

인공지능(Artificial Intelligence, AI)
- 인간의 지능을 모방하여 사람이 하는 일을 컴퓨터(기계)가 할 수 있도록 하는 기술

- 인공지능을 구현하는 방법으로 머신 러닝 (machine learning)과 답러닝(deep learning)이 있음

**인공지능 > 머신 러닝 > 딥러닝**

<img src="https://drive.google.com/uc?export=view&id=1tCjtruIOnwU-594BZAJq7irawUpe1aF5" width="300">


머신 러닝
- 주어진 데이터를 인간이 먼저 처리(전처리)

- 이미지 데이터라면 사람이 학습 데이터를 컴퓨터가 인식할 수 있도록 준비해 두어야 함

- 범용적인 목적을 위해 제작된 것으로 데이터이 특징을 스스로 추출하지 못함

- 머신 러닝의 학습 과정은 각 데이터(혹은 이미지) 특성을 컴퓨터(기계)에 인식시키고 학습시켜 문제를 해결

답러닝
- 인간이 하던 작업을 생략

- 대량의 데이터를 신경망에 적용하면 컴퓨터가 스스로 분석한 후 답을 찾음

<img src="https://drive.google.com/uc?export=view&id=1k3WyohVtgchJ-coTFI78Plx2rTgt8vLP" width="500">



## 02. 머신 러닝이란

### 1) 머신 러닝 학습 과정

머신 러닝: 크게 학습 단계(learning)와 예측 단계(prediction)로 구분할 수 있음

<img src="https://drive.google.com/uc?export=view&id=1FHPc-vxiC8RwXT76I7oRU1_2vxOnRgJP" width="500">

머신 러닝의 주요 구성 요소는 데이터와 모델(모형)

- 데이터: 머신 러닝이 학습 모델을 만드는 데 사용하는 것으로 훈련 데이터가 나쁘다면 실제 현상의 특성을 제대로 반영할 수 없으므로 실제 데이터의 특정이 잘 반영되고 편향되지 않는 훈련 데이터를 확보하는 것이 중요 / 학습에 필요한 데이터가 수집되었다면 훈련 데이터셋'과 '테스트 데이터셋' 용도로 분리해서 사용

- 모댈은 머신 러닝의 학습 단계에서 얻은 최종 결과물로 가설이라고도 함

모델의 학습절차
1. 모델(또는가설) 선택
2. 모델 학습 및 평가
3. 평가를 바탕으로 모델 업데이트


### 2)  머신 러닝 학습 알고리즘

머신 러닝의 학습 알고리즘으로는 지도 학습 비지도 학습 강화 학습이 있음

- 지도 학습: 이름에서 알 수 있듯이 정답이 무엇인지 컴퓨터에 알려 주고 학습시키는 방법

- 비지도 학습: 정답을 알려 주지 않고 특정(다리 길이가 짧은 초식 동물)이 비슷한 데이터(토끼，다람쥐)를 클러스터링(범주화)하여 예측하는 학습 방법

- 강화 학습: 자신의 행동에 대한 보상을 받으며 학습을 진행

지도 학습，비지도 학습，강화 학습에서 지주 사용되는 알고리즘

<img src="https://drive.google.com/uc?export=view&id=1SR7ACacxAz8Tmy6bPaVIGRnJr-FKPMuV" width="600">



## 03. 딥러닝이란

딥러닝: 인간의 신경망 원리를 모방한 심층 신경망 이론을 기반으로 고안된 머신 러닝 방법의 일종

즉，딥러닝이 머신 러닝과 다른 큰 차이점: 인간의 뇌를 기초로 하여 설계했다는 점

<img src="https://drive.google.com/uc?export=view&id=1EGWQUy-UeSPNwbQO2v0YSWLUUprTWWTd" width="300">

- 수상돌기: 주변이나 다른 뉴런에서 자극을 받아들이고，이 자극들을 전기적 신호 형태로 세포체와 축삭돌기로 보내는 역할

- 시냅스: 신경 세포들이 이루는 연결 부위로 한 뉴런의 축삭돌기와 다음 뉴런의 수상돌기가 만나는 부분

- 축삭돌기: 다른 뉴런(수상돌기)에 신호를 전달하는 기능을 하는 뉴런의 한 부분. 뉴런에서 뻗어 있는 돌기 중 가장 길며，한 개만 있음

- 축삭말단: 전달된 전기 신호를 받아 신경 전달 물질을 시냅스 틈새로 방출

### 1) 딥러닝 학습 과정

<img src="https://drive.google.com/uc?export=view&id=1wyjQzTKjLZASuPc5GoFsvKl7NkYGR6RU" width="200">

- 모델(모형) 정의: 모벨(모형) 정의 단계에서 신경망을 생성. 일반적으로 은닉층 개수가 많을수록 성능이 좋아지지만 과적합이 발생할 획률이 높음 / 은닉층 개수에 따른 성능과 과적합은 서로 상충 관계에 있다고 할 수 있음

- 모델(모형) 컴파일: 컴파일 단계에서 활성화 함수, 손실 함수, 옵티마이저를 선택 / 데이터 형태에 따라 다양한 옵션이 가능. 훈련 데이터셋 형태가 연속형이라면 평균 제곱 오차(MSE) 를 사용할 수 있으며, 이진 분류라면 크로스 엔트로피 선택. 과적합을 피할 수 있는 활성화 함수 및 옵티마이저 선택이 중요

- 모델(모형) 훈련: 훈련 단계에서는 한 번에 처리할 데이양을 지정 / 전체 훈련 데이터셋에서 일정한 묶음으로 나누어 처리할 수 있는 배치와 훈련의 횟수인 에포크 선택이 중요. 이때 훈련 과정에서 값의 변화를 시각적으로 표현하여 눈으로 확인하면서 파라미터와 하이퍼파라미터에 대한 최적의 값을 찾을 수 있어야 함.

- 모델(모형) 예측: 검증 데이터셋을 생성한 모델(모형)에 적용하여 실제로 예측을 진행해 보는 단계. 이때 예측력이 낮다면 파라미터를 튜닝하거나 신경망 자체를 재설계해야 할 수도 있음


### 2) 딥러닝 학습 알고리즘

딥러닝 학습 알고리즘: 활용분야에 따라 지도학습, 비지도
학습，전이 학습으로 분류됨

**지도 학습**으로 분류되는 알고리즘

- 합성곱 신경망(CNN) : 목적에 따라 이미지 분류 이미지 인식 이미지 분할로 분류할 수 있음

시계열 데이터를 분류할 때 사용되는 것
- 순환 신경망(RNN): 주시 데이터처럼 시간에 따르 데이터가 있을 때 순환 신경망을 사용하지만, 역전파 과정에서 기울기 소멸 문제가 발생하는 단점이 있음

- LSTM: 이러한 문제점을 개선하고자 게이트(gate) 를 세 개 추가한 것

**비지도 학습**으로는 원드 임베딩과 군집이 있음

- 워드 임베딩: 단어를 벡터로 표현 / 자연어 처리 분야의 일종으로 번역이나 음성 인식 등 서비스에서 사용

- 군집: 아무런 정보가 없는 상태에서 데이터를 분류하는 방법

**전이 학습(transfer learning)**: 사전에 학습이 완료된 모델을 가지고 우리가 원하는 학습에 미세 조정 기법을 이용하여 학습시키는 방법
- 사전 학습 모델: 풀고자 하는 문제와 비슷하면서 많은 데이터로 이미 학습이 되어 있는 모댈


# Chapter 02.실습 환경 설정과 파이토치 기초

## 01. 파이토치 개요

파이토치 (PyTorch)는 2017년 초에 공개된 답러닝 프레임워크로 루아(Lua) 언어로 개발되었던 토치
(Torch)를 페이스북에서 파이써 버전으로 내놓은 것

### 1) 파이토치 특징 및 장점

파이토치 특징: **GPU에서 텐서 조작 및 동적 신경망 구축이 가능한 프레임워크**

GPU(Graphics Processing Unit) : 연산 속도를 빠르게 하는 역할

- 딥러닝에서는 기울기를 계산할 때 미분을 쓰는데, GPU를 사용하면 빠른 계산이 가능

- 내부적으로 CUDA, cuDNN이라는 API를 통해 GPU를 연산에 사용할 수 있음  
- 병렬 연산에서 GPU의 속도는 CPU의 속도보다 훨씬 빠르므로 딥러닝 학습에서 GPU 사용은 필수라고 할 수 있음  
텐서(Tensor): 파이토치에서 텐서 의미는 다음과 같음

- 텐서는 파이토치의 데이터 형태

- 텐서는 단일 데이터 형식으로 된 자료들의 다차원 행렬

- 텐서는 간단한 명령어(변수 뒤에 .cuda()를 추가)를 시용해서 GPU로 연산을 수행하게 할 수 있음

- 동적 신경망: 훈련을 반복할 때마다 네트워크 변경이 가능한 신경망을 의미. 예를 들어 학습 중에 은닉층을 추가하거나 제거하는 등 모델의 네트워크 조작이 가능
- 연산 그래프를 정의하는 것과 동시에 값도 초기화되는 'Define by Run' 방식을 사용

파이토치 장점
- 단순함(효율적인 계산)
  - 파이썬 환경과 쉽게 통합할 수 있음
  - 디버깅이 직관적이고 간결함

- 성능(낮은 CPU 활용)
  - 모델 훈련을 위한 CPU 사용률이 텐서플로와 비교하여 낮음
  - 학습 및 추론 속도가 빠르고 다루기 쉬움
- 직관적인 인터페이스
  - 텐서플로처럼 잦은 API 변경(layers -> slim -> estimators -> tf.keras) 이 없어 배우기 쉬움



### 2) 파이토치의 아키텍처

파이토치의 아카텍처는 크게 세 개의 계층으로 나눠져 있음

**파이토치 API**
- 가장 상위 계층
- 사용자가 이해하기 쉬운 API를 제공하여 텐서에 대한 처리와 신경망을 구축하고 훈련할 수 있도록 도움
- torch: GPU를 지원하는 텐서 패키지 / torch.autograd: 자동 미분 패키지 / torch.nn: 신경망 구축 및 훈련 패키지 / torch.multiprocessing: 파이썬 멀티프로세싱 패키지 / torch.utils: DataLoader 및 기타 유틸리티를 제공하는 패키지

**파이토치 엔진**
- Autograd C++, Aten C++, JIT C++, Python API로 구성되어 있음

- Autograd C++: 가중치，바이어스를 업데이트하는 과정에서 필요한 미분을 자동으로 계산
- Aten C++: C++ 텐서 라이브러리를 제공
- JIT C++: 계산을 최적화하기 위한 JIT 컴파일러

**연산 처리**
가장 아래 계층에 속하는 C 또는 CUDA 패키지는 상위의 API에서 할당된 거의 모든 계산을 수행


## 02. 파이토치 기초 문법

### 1) 텐서 다루기

**텐서 생성 및 변환**

텐서: 파이토치의 가장 기본이 되는 데이터 구조


In [ ]:
import torch
print(torch.tensor([[1,2],[3,4]])) # 2차원 형태의 텐서 생성
print(torch.tensor([[1,2],[3,4]], device="cuda:0")) # GPU에 텐서 생성
print(torch.tensor([[1,2],[3,4]], dtype=torch.float64)) # dtype을 이용하여 텐서 생성

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], device='cuda:0')
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [ ]:
temp = torch.tensor([[1,2],[3,4]])
print (temp.numpy( )) # 텐서를 ndarray로 변환
temp = torch.tensor([[1,2],[3,4]], device="cuda:0" )
print(temp.to("cpu").numpy()) # GPU상의 텐서를 CPU의 텐서로 변환한 후 ndarray로 변환

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


**텐서의 인덱스 조작**

텐서는 넘파이의 ndarray를 조작하는 것과 유사하게 동작하기 때문에 배열처럼 인덱스를 바로 지정하거나 슬라이스 등을 시용할 수 있음

텐서의 자료형
- torch.FloatTensor: 32비트의 부동 소수점
- torch.DoubleTensor: 64비트의 부동 소수점
- torch.LongTensor: 64비트의 부호가 있는 정수


In [ ]:
temp = torch.FloatTensor([1,2,3,4,5,6,7])
print(temp[0],temp[1],temp[-1]) # 인덱스로 접근
print('------------------------')
print(temp [2:5], temp[4:-1]) # 슬라이스로 접근

tensor(1.) tensor(2.) tensor(7.)
------------------------
tensor([3., 4., 5.]) tensor([5., 6.])


**텐서 연산 및 차원 조작**

In [ ]:
v = torch. tensor([1, 2, 3]) # 길이가 3인 벡터 생성
w = torch.tensor([3, 4, 6])
print(w - v ) # 길이가 같은 벡터 간 뺄셈 연산

tensor([2, 2, 3])


In [ ]:
temp = torch.tensor([
    [1,2],[3,4]]) # 2 x 2 행렬 생성
print(temp.shape)
print('------------------------')
print(temp.view(4,1))## 2 x 2 행렬을 4 x 1로 변형
print('------------------------')
print(temp.view(-1)) # 2 x 2 행렬을 1차원 벡터로 변형
print('------------------------')
print(temp.view(1,-1) ) # -1은 (1,?)와 같은 의미로 다른 차원으로부터 해당 값을 유추하겠다는 것.
                        # temp의 원소 개수(2x2=4)를 유지한 채 (1,?)의 형태를 만족해야 하므로 (1,4)가 됩니다.
print('------------------------')
print(temp.view (-1,1)) # 앞에서와 마찬가지로 (?，1)의 의미로 temp의 원소 개수(2x2=4)를 유지한 채 (?,1)의 형태를 만족해야 하므로 (4,1)이 됩니다.

torch.Size([2, 2])
------------------------
tensor([[1],
        [2],
        [3],
        [4]])
------------------------
tensor([1, 2, 3, 4])
------------------------
tensor([[1, 2, 3, 4]])
------------------------
tensor([[1],
        [2],
        [3],
        [4]])


### 2) 데이터 준비

**단순하게 파일을 불러와서 사용**

In [ ]:
# pip install pandas

In [ ]:
# import pandas as pd -- pandas 라이브러리 호출
# import torch -- torch 라이브러리 호출
# data = pd.read_csv ( '.. /class2.csv' ) -- csv 파일을 불러옵니다.

# x = torch .from_numpy(data['x'].values).unsqueeze(dim=1).float() -- CSV 파일의 x 칼럼의 값을 넘파이 배열로 받아 Tensor(dtype)으로 바꾸어 줍니다.
# y = torch .from_numpy(data['y'].values).unsqueeze(dim=1).float() -- CSV 파일의 y 칼럼의 값을 넘파이 배열로 받아 Tensor(dtype)으로 바꾸어 줍니다.

**커스텀 데이터셋을 만들어서 사용**

In [ ]:
# class CustomDataset(torch.utils.data .Dataset):
#   def __init__(self): -- 필요한 변수를 선언하고, 데이터셋의 전처리를 해 주는 함수
#   def __len__(self): -- 데이터셋의 길이. 즉，총 샘플의 수를 가져오는 함수
#   def __getitem__(self, index): -- 데이터셋에서 특정 데이터를 가져오는 함수(index번째 데이터를 반환하는 함수이며，이때 반환되는 값은 텐서의 형태를 취해야 합니다)

In [ ]:
# import pandas as pd
# import torch
# from torch.utils.data import Dataset
# from torch.utils.data import DataLoader

# class CustomDataset (Dataset):
#   def __init__(self, csv_file): # csv_file 파라미터를 통해 데이터셋을 불러옵니다.
#     self.label = pd .read_csv(csv_file)

#   def __len__ (self): # 전체 데이터셋의 크기(size)를 반환합니다.
#     return len(self.label)

#   def __getitem__(self,idx): # 전체 x와 y 데이터 중에 해당 idx번째의 데이터를 가져옵니다.
#     sample = torch.tensor(self.label.iloc[idx, 0:3]).int()
#     label = torch.tensor(self.label.iloc[idx, 3]).int()
#     return sample, label

# tensor_dataset = CustomDataset(' .. /covtype.csv') # 데이터셋으로 covtype.csv를 사용합니다.
# dataset = DataLoader(tensor_dataset, batch_size=4, shuffle=True) # 데이터셋을 torch. utils.data. DataLoader에 파라미터로 전달합니다.

**파이토치에서 제공하는 데이터셋 사용**

In [ ]:
# pip install requests

In [ ]:
# import torchvision.transforms as transforms

# mnist_transform = transforms.Compose([
#     transforms.ToTensor(),
#     transforms.Normalize((0.5,), (1.0,))
# ]) # 평균이 0.5, 표준편차가 1.0이 되도록 데이터의 분포(normalize)를 조정

# from torchvision.datasets import MNIST
# import requests
# download_root = '../chap02/data/MNIST_DATASET' # 내려받을 경로 지정

# train_dataset = MNIST(download_root, transform=mnist_transform, train=True,
#                       download=True) # 훈련(training) 데이터셋

# valid_dataset = MNIST(download_root, transform=mnist_transform, train=False,
#                       download=True) # 검증(validation) 데이터셋

# test_dataset = MNIST(download_root, transform=mnist_transform, train=False,
#                      download=True) # 테스트(test) 데이터셋

### 3) 모델 정의

- 계층(layer): 모듈 또는 모듈을 구성하는 한 개의 계층으로 합성곱층, 선형계층 등이 있음

- 모듈(module): 한 개 이상의 계층이 모여서 구성된 것으로, 모듈이 모여 새로운 모듈을 만들 수도 있음

- 모델(model): 최종적으로 원하는 네트워크로, 한 개의 모듈이 모델이 될 수도 있음


**단순 신경망을 정의하는 방법**

model = nn.Linear(in_features=1, out_features=1, bias=True)

**nn.Module( )을 상속하여 정의하는 방법**





In [ ]:
# class MLP(Module):
#   def __init__(self, inputs):
#     super(MLP, self).__init__()
#     self.layer = Linear(inputs, 1) # 계층 정의
#     self.activation = Sigmoid() # 활성화 함수 정의

#   def forward(self, X):
#     X = self.layer(X)
#     X = self.activation(X)
#     return X

**Sequential 신경망을 정의하는 방법**

In [ ]:
import torch.nn as nn
class MLP(nn .Module ):
  def __init__(self):
    super(MLP, self).__init__()
    self.layer1 = nn.Sequential(
        nn.Conv2d(in_channels=3, out_channels=64, kernel_size=5),
        nn.ReLU(inplace=True ),
        nn.MaxPool2d(2))

    self.layer2 = nn.Sequential(
        nn.Conv2d(in_channels=64, out_channels=30, kernel_size=5),
        nn.ReLU(inplace=True),
        nn.MaxPool2d(2))

    self.layer3 = nn.Sequential(
        nn.Linear(in_features=30*5*5, out_features=10, bias=True ),
        nn.ReLU(inplace=True ))

    def forward (self, x):
      x = self.layer1(x)
      x = self.layer2(x)
      x = x.view(x .shape[0] , -1)
      x = self.layer3(x)
      return x
model = MLP() # 모델에 대한 객체 생성

print("Printing children\n-----------------------")
print(list(model.children()))
print("\n\nPrinting Modules\n-----------------------")
print(list(model.modules()))

Printing children
-----------------------
[Sequential(
  (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Linear(in_features=750, out_features=10, bias=True)
  (1): ReLU(inplace=True)
)]


Printing Modules
-----------------------
[MLP(
  (layer1): Sequential(
    (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer3): Sequential(
    (0): Linear(in_features=

**함수로 신경망을 정의하는 방법**

In [ ]:
def MLP (in_features=1, hidden_features=20, out_features=1):
  hidden = nn.Linear(in_features=in_features , out_features=hidden_features ,
                     bias=True)
  activation = nn.ReLU()
  output = nn.Linear(in_features=hidden_features, out_features=out_features,
                     bias=True )
  net = nn.Sequential(hidden, activation, output)
  return net

### 4) 모델의 파라미터 정의

- 손실 함수(loss function): 학습하는 동안 출력과 실제 값(정답) 사이의 오차를 측정

- 옵티마이저(optimizer): 데이터와 손실 함수를 바탕으로 모델의 업데이트 방법을 결정함

- 학습률 스케줄러(learning rate scheduler): 미리 지정한 횟수의 에포크를 지날 때마다 학습률을 감소시켜 줌

- 지표(metrics): 훈련과 테스트 단계를 모니터링 함

In [ ]:
# from torch.optim import optimizer
# criterion = torch.nn.MSELoss()
# optimizer = torch.optim.SGD(model.parameters() , 1r= 0.01, momentum=0.9)
# scheduler = torch.optim.1r_scheduler.LambdaLR(optimizer=optimizer,
#                                               1r_lambda=lambda epoch: 0.95 ** epoch)
# for epoch in range (1, 100+1): # 에포크 수만큼 데이터를 반복하여 처리
#   for x, y in dataloader: # 배치 크기만큼 데이터를 가져와서 학습 진행
#       optimizer.zero_grad()
# loss_fn(model(x), y) .backward()
# optimizer.step()
# scheduler.step()

### 5) 모델 훈련

In [ ]:
# for epoch in range (100):
#   yhat = model(x_train)
#   loss = criterion(yhat, y_train)
#   optimizer.zero_grad () # 오차가 중칩적으로 쌓이지 않도록 초기화
#   loss.backward()
#   optimizer.step()

### 6) 모델 평가


In [ ]:
pip install torchmetrics

In [ ]:
import torch
import torchmetrics

preds = torch.randn(10, 5).softmax(dim=-1)
target = torch.randint(5,(10,))

acc = torchmetrics.functional.accuracy(preds, target, task='multiclass', num_classes=5)

In [ ]:
import torch
import torchmetrics
metric = torchmetrics.Accuracy(task='multiclass', num_classes=5) # 모델 평가(정확도) 초기화

n_batches = 10
for i in range (n_batches):
  preds = torch.randn(10, 5).softmax(dim=-1)
  target = torch.randint(5, (10,))

  acc = metric (preds, target)
  print (f"Accuracy on batch {i}: {acc}") # 현재 배치에서 모델 평가(정확도)
acc = metric .compute()
print(f"Accuracy on all data: {acc}") # 모든 배치에서 모델 평가(정확도)

Accuracy on batch 0: 0.4000000059604645
Accuracy on batch 1: 0.0
Accuracy on batch 2: 0.20000000298023224
Accuracy on batch 3: 0.10000000149011612
Accuracy on batch 4: 0.20000000298023224
Accuracy on batch 5: 0.4000000059604645
Accuracy on batch 6: 0.4000000059604645
Accuracy on batch 7: 0.20000000298023224
Accuracy on batch 8: 0.0
Accuracy on batch 9: 0.20000000298023224
Accuracy on all data: 0.20999999344348907


### 7) 훈련 과정 모니터링

In [ ]:
# pip install tensorboard

In [ ]:
# import torch
# from torch.utils.tensorboard import SummaryWriter
# writer = SummaryWriter(".. / chap02/tensorboard") # 모니터링에 필요한 값들이 저장될 위치

# for epoch in range (num_epochs):
#   model.train () # 학습 모드로 전환(dropout=True)
#   batch_loss = 0.0

#   for i, (x, y) in enumerate (dataloader):
#     x, y = x.to(device).float(), y.to(device).float()
#     outputs = model(x)
#     loss = criterion(outputs, y)
#     writer.add_scalar("Loss", loss, epoch) # 스칼라 값(오차)을 기록
#     optimizer.zero_grad()
#     loss.backward()
#     optimizer.step()

# writer.close() # SummaryWriter가 더 이상 필요하지 않으면 close() 메서드 호출

In [ ]:
# tensorboard --logdir=.. /chap02/tensorboard --port=6006