<a href="https://colab.research.google.com/github/miso-20/ESSA/blob/main/ESAA_OB_WEEK_03_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

파이썬 머신러닝 완벽가이드 ch9. p.584~601

# Chapter 09. 추천 시스템

## 01. 추천 시스템의 개요와 배경

### 1) 추천 시스템의 개요

- 하나의 콘텐츠를 선택했을 때 선택된 콘텐츠와 연관된 추천 콘텐츠가 얼마나 사용자의 관심을 끌고 개인에게 맞춘 콘텐츠를 추천했는지는 그 사이트의 평판을 좌우하는 매우 중요한 요소

- 추천 시스템의 묘미는 사용자 자신도 좋아하는지 몰랐던 취향을 시스템이 발견하고 그에 맞는 콘텐츠를 추천해주는 것

### 2) 온라인 스토어의 필수 요소, 추천 시스템

- 추천 시스템 특히 온라인에서 진가를 발휘

- 좋은 추천 시스템: 사용자가 무엇을 원하는지 빠르게 찾아내 사용자의 온라인 쇼핑의 즐거움을 배가 함

- 온라인 스토어에서 추천 시스템은 필수 구성 요소

- 온라인 스토어는 많은 양의 고객과 상품 관련 데이터를 가지고 있음

- 다음과 같은 데이터가 추천 시스템을 구성하는 데 사용될 수 있음

  - 사용자가 어떤 상품을 구매했는가?
  - 사용자가 어떤 상품을 둘러보거나 장바구니에 넣었는가?
  - 사용자가 평가한 영화 평점은? 제품 평가는?
  - 사용자가 스스로 작성한 자신의 취향은?
  - 사용자가 무엇을 클릭했는가?

### 3) 추천 시스템의 유형

추천 시스템: 크게 **콘텐츠 기반 필터링**(Content based filtering) 방식과 **협업 필터링**(Collaborative Filtering) 방식으로 나뉨

- 협업 필터링 방식: 다시 **최근접 이웃**(Nearest Neighbor) 협업 필터링과 **잠재 요인**(Latent Factor) 협업 필터링으로 나뉨

## 02. 콘텐츠 기반 필터링 추천 시스템

콘텐츠 기반 필터링 방식: 사용자가 특정한 아이템을 매우 선호하는 경우, 그 아이템과 비슷한 콘텐츠를 가진 다른 아이템을 추천하는 방식

ex) 사용자가 특정 영화에 높은 평점을 줬다면 그 영화의 장르, 출연 배우, 감독, 영화 키워드 등의 콘텐츠와 유사한 다른 영화를 추천해주는 방식

<img src="https://drive.google.com/uc?export=view&id=10VTz1-3UEG7a_ZLYHBSZac55UYBtuKZI" width="500">

## 03. 최근접 이웃 협업 필터링

협업 필터링(Collaborative Filtering) 방식: 친구들에게 물어보는 것과 유사한 방식으로, 사용자가 아이템에 매긴 평점 정보나 상품 구매 이력과 같은 사용자 행동 양식(User Behavior)만을 기반으로 추천을 수행하는 것

- 주요 목표: 사용자-아이템 평점 매트릭스와 같은 축적된 사용자 행동 데이터를 기반으로 사용자가 아직 평가하지 않은 아이템을 예측 평가(Predicted Rating)하는 것

- **최근접 이웃 방식**과 **잠재 요인 방식**으로 나뉘며, 두 방식 모두 사용자-아이템 평점 행렬 데이터에만 의지해 추천을 수행

- 협업 필터링 알고리즘에 사용되는 사용자-아이템 평점 행렬에서 행(Row)은 개별 사용자, 열(Column)은 개별 아이템으로 구성되며, 사용자 아이디 행, 아이템 아이디 열 위치에 해당하는 값이 평점을 나타내는 형태가 돼야 함

- 만약 데이터가 다음 그림의 왼쪽과 같이 레코드 레벨 형태인 사용자-아이템 평점 데이터라면 판다스의 pivot_table()과 같은 함수를 이용해 그림의 오른쪽과 같은 형태인 사용자-아이템 평점 행렬 형태로 변경해야 함

<img src="https://drive.google.com/uc?export=view&id=1Iy951E-5rcnHx2EVR6mijwVlxh8rGXJr" width="500">


- **최근접 이웃 협업 필터링** : 메모리(Memory) 협업 필터링이라고도 하며, 일반적으로 **사용자 기반**과 **아이템 기반**으로 다시 나뉠 수 있음

  - 사용자 기반(User—User): 당신과 비슷한 고객들이 다음 상품도 구매했습니다(Customers like you also bought these items).
  
  - 아이템 기반(Item네em): 이 상품을 선택한 다른 고객들은 다음 상품도 구매했습니다(customers who bought this item also bought these items).

- **사용자 기반 최근접 이웃 방식**: 특정 사용자와 유사한 다른 사용자를 Top-N으로 선정해 이 Top-N 사용자가 좋아하는 아이템을 추천하는 방식
  
    즉, 특정 사용자와 타 사용자 간의 유사도(Similarity)를 측정한 뒤 가장 유사도가 높은 Top-N 사용자를 추출해 그들이 선호하는 아이템을 추천하는 것

  <img src="https://drive.google.com/uc?export=view&id=1DEZGF1SZlQLN5lMy6FDQLYf_4ffrBYTT" width="400">

- **아이템 기반 최근접 이웃 방식**: 아이템이 가지는
속성과는 상관없이 사용자들이 그 아이템을 좋아하는지/싫어하는지의 평가 척도가 유사한 아이템을 추천하는 기준이 되는 알고리즘

  <img src="https://drive.google.com/uc?export=view&id=15TAk-h2BNxh3y94ITJmMuVufcg5AlNrG" width="400">



## 04. 잠재 요인 협업 필터링

### 1) 잠재 요인 협업 필터링의 이해

잠재 요인 협업 필터링
- 사용자-아이템 평점 매트릭스 속에 숨어 있는 잠재 요인을 추출해 추천 예측을 할 수 있게 하는 기법
- 숨겨져 있는 '잠재 요인'을 기반으로 분해된 매트릭스를 이용해 사용자
가 아직 평가하지 않은 아이템에 대한 예측 평가를 수행하는 것

행렬 분해(Matrix Factorization)
- 대규모 다차원 행렬을 SVD와 같은 차워 감소 기법으로 분해하는 과정에서 잠재 요인을 추출하는 방법

- 사용자-아이템 평점 행렬과 같이 다차원의 매트릭스를 저차원의 매트릭스로 분해하는 기법


다음 그림은 이러한 행렬 분해 기법을 이용해 사용자-잠재 요인 행렬과 아이템- 잠재 요인 행렬의 전치 행렬（즉, 잠재 요인-아이템 행렬）로 분해된 데이터 세트를 다시 내적 곱으로 결합하면서 사용자가 예측하지 않은 아이템에 대한 평점을 도출하는 방식을 개략적으로 나타낸 것

<img src="https://drive.google.com/uc?export=view&id=1tN1IfcNIO8GNe6RXoTeXugXTsWsK1UG_" width="500">


### 2) 행렬 분해의 이해

행렬 분해
- 다차원의 매트릭스를 저차원 매트릭스로 분해하는 기법으로서 대표적으로 SVD(Singular
Vector Decomposition), NMF(Non—Negative Matrix Factorization) 등이 있음

- M개의 사용자(User) 행과 N개의 아이템(item) 열을 가진 평점 행렬 R은 M X N 차원으로 구성되며,
행렬 분해를 통해서 사용자-K 차원 잠재 요인 행렬 P(P 는 MXK 차원와 K 차원 잠재 요인-아이템 행렬 Q.T(Q.T 는 KXN 차원로 분해될 수 있음

-  R = P*Q.T

    - M: 총 사용자 수
    - N: 총 아이템 수
    - K: 잠재 요인의 차원 수
    - R: M X N 차원의 사용자-아이템 평점 행렬
    - P: 사용자와 잠재 요인과의 관계 값을 가자는 MXK 차원의 사용자-잠재 요인 행렬
    - Q: 아이템과 잠재 요인과의 관계 값을 가지는 NXK 차원의 아이템-잠재 요인 행렬
    - Q.T는 Q 매트릭스의 행과 열 값을 교환한 전치 행렬


- 행렬 분해는 주로 SVD(Singular Value Decomposition) 방식을 이용. 하지만 SVD는 널(NaN) 값이 없는 행렬에만 적용할 수 있음.
R 행렬에는 아직 평점이 되지 않은 많은 널 값이 있기 때문에 P와 Q 행렬을 일반적인 SVD 방식으로는 분해할 수가 없음. 이러한 경우에는 **확률적 경사 하강법** (Stochastic Gradient Descent, SGD)이나 **ALS**(Alternating Least Squares) 방식을 이용해 SVD를 수행함


### 3) 확률적 경사 하강법을 이용한 행렬 분해

확률적 경사 하강법(Stochastic Gradient Descent)
- 경사 하강법의 한 종류

-  P와 Q 행렬로 계산된 예측 R 행렬 값이 실제 R 행렬 값과 가장 최소의 오류를 가질 수 있도록 반복적인 비용 함수 최적화를 통해 P와 Q를 유추해내는 것

확률적 경사 하강법(이하 SGD)을 이용한 행렬 분해의 절차
1. P와 Q를 임의의 값을 가진 행렬로 설정
2. P와 Q.T 값을 곱해 예측 R 행렬을 계산하고 예측 R 행렬과 실제 R 행렬에 해당하는 오류 값을 계산
3. 이 오류 값을 최소화할 수 있도록 P와 Q 행렬을 적절한 값으로 각각 업데이트 함
4. 만족할 만한 오류 값을 가질 때까지 2, 3번 작업을 반복하면서 P와 Q 값을 업데이트해 근사화 함

실제 값과 예측값의 오류 최소화와 L2 규제(Regularization)를 고려한 비용 함수식
<img src="https://drive.google.com/uc?export=view&id=1VGgBXm8zWp6weX6lpo4If-VWDHQvkRco" width="300">

일반적으로 사용자-아이템 평점 행렬의 경우 행렬 분해를 위해서 단순히 예측 오류값의 최소화와 학습
시 과적합을 피하기 위해서 규제를 반영한 비용 함수를 적용함. 그리고 위의 비용 함수를 최소화하기 위해서 새롭게 업데이트되는 P'u와 Q'i는 다음과 같이 계산할 수 있음

  <img src="https://drive.google.com/uc?export=view&id=1WXtEorSd0pw32x4YT1PMC7w8ubpsIRqG" width="300">


In [ ]:
import numpy as np

# 원본 행렬 R 생성, 분해 행렬 P와 Q 초기화, 잠재 요인 차원 K는 3으로 설정.
R = np.array([[4, np.nan, np.nan, 2, np.nan],
              [np.nan, 5, np.nan, 3, 1],
              [np.nan, np.nan, 3, 4, 4],
              [5, 2, 1, 2, np.nan]])
num_users, num_items = R.shape
K=3

# P와 Q 행렬의 크기를 지정하고 정규 분포를 가진 임의의 값으로 입력합니다.
np.random.seed(1)
P = np.random.normal(scale=1./K, size=(num_users, K))
Q = np.random.normal(scale=1./K, size=(num_items, K))

In [ ]:
from sklearn.metrics import mean_squared_error

def get_rmse(R, P, Q, non_zeros):
  error = 0
  # 두 개의 분해된 행렬 으와 Q.T의 내적으로 예측 R 행렬 생성
  full_pred_matrix = np.dot(P, Q.T)

  # 실제 R 행렬에서 널이 아닌 값의 위치 인덱스 추출해 실제 R 행렬과 예측 행렬의 RMSE 추출
  x_non_zero_ind = [non_zero[0] for non_zero in non_zeros]
  y_non_zero_ind = [non_zero[1] for non_zero in non_zeros]
  R_non_zeros = R[x_non_zero_ind, y_non_zero_ind]
  full_pred_matrix_non_zeros = full_pred_matrix[x_non_zero_ind, y_non_zero_ind]
  mse = mean_squared_error(R_non_zeros, full_pred_matrix_non_zeros)
  rmse = np.sqrt(mse)

  return rmse

In [ ]:
# R > 0인 행 위치, 열 위치, 값을 non_zeros 리스트에 저장.
non_zeros = [ (i, j, R[i, j]) for i in range(num_users) for j in range(num_items) if R[i, j]> 0 ]

steps=1000
learning_rate=0.01
r_lambda=0.01

# SGD 기법으로 P와 Q 매트릭스를 계속 업데이트.
for step in range(steps):
  for i, j, r in non_zeros:
    # 실제 값과 예측 값의 차이인 오류 값 구함
    eij = r - np.dot(P[i, :], Q[j, :].T)
    # Regularization을 반영한 SGD 업데이트 공식 적용
    P[i, :] = P[i, :] + learning_rate*(eij * Q[j, :] - r_lambda*P[i, :])
    Q[j, :] = Q[j, :] + learning_rate*(eij * P[i, :] - r_lambda*Q[j, :])

    rmse = get_rmse(R, P, Q, non_zeros)
    if (step % 50) == 0:
      print("### iteration step : ", step, " rmse : ", rmse)

### iteration step :  0  rmse :  3.261355059488935
### iteration step :  0  rmse :  3.26040057174686
### iteration step :  0  rmse :  3.253984404542389
### iteration step :  0  rmse :  3.2521583839863624
### iteration step :  0  rmse :  3.252335303789125
### iteration step :  0  rmse :  3.251072196430487
### iteration step :  0  rmse :  3.2492449982564864
### iteration step :  0  rmse :  3.247416477570409
### iteration step :  0  rmse :  3.241926055455223
### iteration step :  0  rmse :  3.2400454107613084
### iteration step :  0  rmse :  3.240166740749792
### iteration step :  0  rmse :  3.2388050277987723
### iteration step :  50  rmse :  0.5003190892212748
### iteration step :  50  rmse :  0.5001616291326989
### iteration step :  50  rmse :  0.49899601202578087
### iteration step :  50  rmse :  0.4988483450145831
### iteration step :  50  rmse :  0.49895189256631756
### iteration step :  50  rmse :  0.49833236830090993
### iteration step :  50  rmse :  0.4984148489378701
### iterati

In [ ]:
pred_matrix = np.dot(P, Q.T)
print('예측 행렬:\n', np.round(pred_matrix, 3))

예측 행렬:
 [[3.991 0.897 1.306 2.002 1.663]
 [6.696 4.978 0.979 2.981 1.003]
 [6.677 0.391 2.987 3.977 3.986]
 [4.968 2.005 1.006 2.017 1.14 ]]
