<a href="https://colab.research.google.com/github/miso-20/ESSA/blob/main/ESAA_YB_WEEK_01_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

파이썬 머신러닝 완벽 가이드 ch1. p.1~38 필사

# Chapter 01. 파이썬 기반의 머신러닝과 생태계 이해

## 01. 머신러닝의 개념

머신러닝(Machine Learning): 애플리케이션을 수정하지 않고도 데이터를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘 기법
- 데이터를 기반으로 숨겨진 패턴을 인지해 해결
- 머신러닝 알고리즘은 신뢰도를 강화하고 예측 오류를 최소화하기 위한 다양한 수학적 기법을 적용해 데이터 내의 패턴을 스스로 인지하고 신뢰도 있는 예측 결과를 도출

### 1) 머신러닝의 분류

- 지도학습 : **분류**, **회귀**, 추천시스템, 시각/음성감지/인지, 텍스트 분석, NLP

- 비지도학습: 클러스터링, 차원 축소, 강화학습

### 2) 데이터 전쟁
머신러닝의 가장 큰 단점: 데이터에 매우 의존적

머신러닝 모델을 개선: 데이터를 이해하고 효율적으로 가공, 처리, 추출해 최적의 데이터를 기반으로 알고리즘을 구동할 수 있도록 준비

### 3) 파이썬과 R 기반의 머신러닝 비교
머신러닝 프로그램을 작성할 수 있는 대표적인 오픈 소스 프로그램 언어:  파이썬, R
-  R : 통계 전용 프로그램 언어

-  파이썬 : 다양한 영역에서 사용되는 개발 전문 프로그램 언어

파이썬이 R에 비해 뛰어난 점
1. 쉽고 뛰어난 개발 생산성
2. 많은 라이브러리로 인해 개발 시 높은 생산성을 보장
3. 속도는 느리지만, 대신에 뛰어난 확장성, 유연성, 호환성으로 인해 다양한 영역에서 사용
4. 다양한 애플리케이션 개발이 가능
5. 다양한 기업 환경으로의 확산이 가능
6. 유수의 딥러닝 프레임워크인 텐서플로(TensorFlow), 케라스(Keras), 파이토치(PyTorch) 등에서 **파이썬 우선 정책**으로 파이썬을 지원

## 02. 파이썬 머신러닝 생태계를 구성하는 주요 패키지
- 머신러닝 패키지 : 사이킷런(Scikit-Learn)

- 행렬/선형대수/통계 패키지 : **넘파이(NumPy)** / 사이파이(SciPy)

- 데이터 핸들링 : **판다스**(데이터 처리 패키지)는 2차원 데이터 처리에 특화되어 있으며 넘파이보다 훨씬 편리하게 데이터 처리를 할 수 있는 많은 기능을 제공

- 시각화 : 맷플롯립(코드가 길어져 효율 떨어짐) /
시본(Seaborn)은 맷플롯립 보완, 세밀한 부분의 제어는 맷플롯립의 API를 그대로 사용


## 03. 넘파이
넘파이 (NumPy) : 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지
- 빠른 배열 연산 속도를 보장
- 저수준 언어(C/C++) 기반의 호환 API 를 제공
- 데이터 핸들링 기능을 제공 -> 판다스가 더 편리

### 1) 넘파이 ndarray 개요

In [ ]:
import numpy as np  ## as np: 약어로 모듈을 표현해주는 게 관례

넘파이의 기반 데이터 타입 : ndarray ->  다차원 배열을 쉽게 생성하고 다양한 연산을 수행

array() 함수 :  다양한 인자를 입력받아서 ndarray로 변환하는 기능

 -  shape 변수 : 행과 열의 수를 튜플 형태로 가짐 -> ndarray 배열의 차원 알 수 있음

np.array() : 객체를 인자로 입력하면 ndarray로 반환
- ndarray.shape : ndarray의 차원과 크기를 튜플(tuple) 형태로 나타냄

   + 튜플의 형태

     1차원: (요소개수, )

     2차원: (행, 열)

     3차원: (깊이, 행, 열)

In [ ]:
array1 = np.array([1,2,3])
print('array1 type：',type(array1))
print('array1 array 형태:', array1.shape) ## 1차원 배열로 3개의 데이터를 가짐

array2 = np.array([[1,2,3],
                   [2,3,4]])
print('array2 type：',type(array2))
print('array2 array 형태:', array2.shape) ## 2차원 배열로 2행 3열 -> 6개의 데이터를 가짐

array3 = np.array([[1,2,3]])
print('array3 type：', type(array3))
print('array3 array 형태:', array3.shape) ## 2차원 배열로 1행 3열

array1 type： <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type： <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type： <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


ndarray.ndim -> 각 array의 차원을 확인

* [ ]는 : 1차원 , [[ ]] : 2차원


In [ ]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'
      .format(array1.ndim,array3.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


   ### 2) ndarray의 데이터 타입

ndarray내의 데이터값 : 숫자 값, 문자열 값, 불 값 등이 모두 가능

- 숫자형의 경우 : int형, unsigned int형, float형, complex 타입

ndarray 내의 데이터 타입 : 같은 데이터 타입만 가능,  dtype 속성(int, float 등)으로 확인

In [ ]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


ndarray 내의 데이터 타입이 다른 경우 : 데이터 크기가 더 큰 데이터 타입으로 형 변환

In [ ]:
list2 = [1, 2, 'test'] ## int형, 문자열: int형이 유니코드 문자열 값으로 변환
array2 = np.array(list2)
print(array2, array2.dtype) ## 숫자형 값 1, 2가 모두 문자열 값으로 변환

list3 = [1, 2, 3.0] ## int형, floaat형: float64형으로 변환
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


ndarray 내 데이터값의 타입 변경 :  astype( ) 메서드를 이용 -> astype( )에 인자로 원하는 타입을 문자열로 지정
- 데이터 타입변경 : 메모리 절약할 때 이용

In [ ]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64') ## int32형 데이터를 float64로 변환
print(array_float, array_float.dtype)

array_int1= array_float.astype('int32') ## float64를 int32로 변환
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1 ])
array_int2= array_float1.astype('int32') ## float64를 int32로 변환
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32



### 3) ndarray를 편리하게 생성하기 一 arange, zeros, ones
 - 테스트용으로 데이터를 만들거나 대규모의 데이터를 일괄적으로 초기화해야 할 경우에
사용

arange( ) : array를 range()로 표현하는 것

In [ ]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


zeros() : 모든 값을 **0**으로 채운 해당 shape를 가진 ndarray를 반환

ones() : 모든 값을 **1**로 채운 해당 shape를 가진 ndarray를 반환

◾ 함수 인자로 dtype을 정해주지 않으면  default 로 float64 형의 데이터로 ndarray를 채움

In [ ]:
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### 4) ndarray의 차원과 크기를 변경하는 reshape()

reshape(): ndarray 를 특정 차원 및 크기로 변환

In [ ]:
array1 = np.arange(10)
print('array1: \n', array1)

array2 = array1.reshape(2, 5)
print('array2: \n', array2)

array3 = array1.reshape(5, 2)
print('array3：\n', array3)

array1: 
 [0 1 2 3 4 5 6 7 8 9]
array2: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3：
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
array1.reshape(4,3) ## 지정된 사이즈로 변경이 불가능하면 오류 발생

ValueError: cannot reshape array of size 10 into shape (4,3)

- reshape() -> -1을 인자로 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환

In [ ]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1,5) ## 고정된 5열에 맞는 행을 자동으로 새롭게 생성해 변환
print('array2 shape：', array2.shape)
array3 = array1.reshape(5,-1) ## 고정된 5행에 맞는 열을 자동으로 새롭게 생성해 변환
print('array3 shape：', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape： (2, 5)
array3 shape： (5, 2)


In [ ]:
array1 = np.arange(10) ## -1 사용해도 호환될 수 없는 형태는 변환X
array4 = array1.reshape(-1, 4)

ValueError: cannot reshape array of size 10 into shape (4)

 - reshape(—1,1) -> 여러 개의 행 & 1개의 열을 가진 ndarray로 변환

 - ndarray는 tolist() 메서드를 이용해 리스트 자료형으로 변환 가능

In [ ]:
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d：\n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print('array5：\n', array5.tolist())
print('array5 shape：', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6：\n', array6.tolist())
print('array6 shape：',array6.shape)

array3d：
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5：
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape： (8, 1)
array6：
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape： (8, 1)


### 5) 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)

(1) 특정한 데이터만 추출: 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환

(2) 슬라이싱(Slicing): 슬라이싱은 연속된 인덱스상의 ndarray를 추출하는 방식이다.

':' 기호 사이에 시작 인덱스와 종료 인덱스를 표시하면 시작 인덱스에서 종료 인덱스-1 위치에 있는 데이터의 ndarray를 반환

(3) 팬시 인덱싱(Fancy Indexing): 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray를 반환

(4) 불린 인덱싱(Boolean Indexing): 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터의 ndarray를 반환

(1) 단일 값 추출

1개의 데이터값을 선택-> ndarray 객체에 해당하는 위치의 인덱스 값을 [ ] 안에 입력

In [ ]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1：',array1)
# index는 0부터 시작하므로 arrayl[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value：',value)
print(type(value)) ## ndarray 타입X, ndarray 내의 데이터값을 의미

array1： [1 2 3 4 5 6 7 8 9]
value： 3
<class 'numpy.int64'>


In [ ]:
print('맨 뒤의 값:',array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


- 단일 인덱스를 이용해 ndarray 내의 데이터값도 간단히 수정 가능

In [ ]:
array1[0] = 9
array1[8] = 0
print('array1：', array1)

array1： [9 2 3 4 5 6 7 8 0]


- 다차원 ndarray에서 단일 값 추출

In [ ]:
array1d = np.arange(start=1 , stop=10)
array2d = array1d.reshape(3, 3) ## 1차원 ndarray를 2차원의 3x3 ndarray로 변환
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0, 0]) ##  2차원 ndarray에서 데이터를 추출
print('(row=0, col=1) index 가리키는 값:', array2d[0, 1])
print('(row=1, col=O) index 가리키는 값:', array2d[1, 0])
print('(row=2, col=2) index 가리키는 값:', array2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=O) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


<img src='https://drive.google.com/uc?id=1Wi62Ny5EKRE-wRU1p1MRqkNJKDzsylRU'>

axis 0: 행 방향의 축

axis 1: 열 방향의 축

axis 2: 높이의 축 (3차원)


axis가 생략되면 axis 0을 의미


▪ 로우와 칼럼은 넘파이 ndarray에서는 사용되지 않는 방식


(2) 슬라이싱: ':' 기호를 이용해 연속한 데이터를 슬라이싱해서 추출
-  ':' 기호 앞에 시작 인덱스를 생략하면 자동으로 맨 처음 인덱스인 0으로 간주
-  ':' 기호 뒤에 종료 인덱스를 생략하면 자동으로 맨 마지막 인덱스로 간주
- ':' 기호 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 맨 처음/맨 마지막 인덱스로 간주

In [ ]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
arrayl = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
## 2차원 ndarray에서 슬라이싱
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print('array 2d:\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])  ## 1차원으로 차원 축소

array 2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray를 반환

3차원 ndarray에서 뒤에 오는 인덱스를 없애면 2차원 ndarray를 반환

In [ ]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape：', array2d[0].shape, 'array2d[1] shape:',array2d[1].shape )

[1 2 3]
[4 5 6]
array2d[0] shape： (3,) array2d[1] shape: (3,)


 (3) 팬시 인덱싱 : 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식

In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)

array3 = array2d[[0, 1], 2] ## 0,1번 행의 2번 열 선택
print('array2d[[0, 1], 2] => ', array3.tolist())

array4 = array2d[[0, 1], 0:2] ## 0,1번 행의 0,1번열 선택
print('array2d[[0,1], 0:2] => ', array4.tolist())

array5 = array2d[[0, 1]] ## 0,1번 행의 모든 열 선택
print('array2d[[0, 1]] => ', array5.tolist())

array2d[[0, 1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0, 1]] =>  [[1, 2, 3], [4, 5, 6]]


(4) 불린 인덱싱 : 조건 필터링과 검색을 동시에 할 수 있기 때문에 매우 자주 사용되 는 인덱싱 방식

- ndarray의 인덱스를 지정하는 [ ] 내에 조건문을 그대로 기재

불린 인덱싱 동작하는 단계

- Step 1: ndarray의 필터링 조건을 [ ] 안에 기재
- Step 2 : True 값에 해당하는 인덱스를 저장
- Step 3 : 저장된 인덱스 값으로 ndarray 조회

In [ ]:
array1d = np.arange(start=1, stop=10)
# [ ] 안에 array 1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array 1d > 5 불린 인덱싱 결과 값 :', array3)

array 1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [ ]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [ ]:
indexes = np.array([5, 6, 7, 8]) ## 인덱스 5,6,7,8이니까 값은 6,7,8,9
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


### 6) 행렬의 정렬 - sort()와 argsort()

(1) 행렬 정렬

np.sort() : 넘파이에서 sort()를 호출하는 방식, 원본 행렬을 변경하지 않고 정렬된 형태로 반환


ndarray.sort() : 행렬 자체에서 sort()를 호출하는 방식, 원본 행렬 자체를 정렬한 값으로 변환하며 반환 값은 None.

In [ ]:
org_array = np.array([ 3, 1, 9, 5])
print('원본 행렬:', org_array)

# np.sort( )로 정렬
sort_array1 = np.sort(org_array)
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort( ) 호출 후 원본 행렬:', org_array)

# ndarray.sort( )로 정렬
sort_array2 = org_array.sort()
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


np.sort()나 ndarray.sort( ) 모두 기본적으로 **오름차순**으로 행렬 내 원소를 정렬

내림차순 정렬은 [：：-1]을 사용

In [ ]:
sort_array1_desc = np.sort(org_array)[::-1]
print ('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


행렬이 2차원 이상일 경우에 axis 축 값 설정을 통해 로우 방향, 또는 칼럼 방향으로 정렬할 수 있음

In [ ]:
array2d = np.array([[8, 12], [7, 1 ]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


(2) 정렬된 행렬의 인덱스를 반환하기

np.argsort() : 정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환

In [ ]:
org_array = np.array([ 3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [ ]:
org_array = np.array([ 3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


argsort() : np.argsort(score_array)를 이용해 반환된 인덱스를 name_array에 팬시 인덱스로 적용해 추출할 수 있음

In [ ]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### 7) 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

(1) 행렬 내적 (행렬 곱)

- np.dot() 을 이용해 계산이 가능


In [ ]:
A = np.array( [[1, 2, 3], [4, 5, 6]] )
B = np.array( [[7, 8], [9, 10], [11, 12]] )

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


(2) 전치 행렬
행과 열 위치를 교환한 원소로 구성한 행렬
- transpose()를 이용해 구할 수 있음

In [ ]:
A = np.array([[1, 2],[3, 4]])
transpose_mat = np.transpose(A)
print ('A 의 전치 행렬:\n', transpose_mat)

A 의 전치 행렬:
 [[1 3]
 [2 4]]
